# Translation of Odoo Server.
# This file contains the translation of the following modules:
#	* auth_signup_verify_email
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 10.0+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-07-03 10:45+0000\n"
"PO-Revision-Date: 2019-07-03 10:45+0000\n"
"Last-Translator: <>\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: auth_signup_verify_email
#: code:addons/auth_signup_verify_email/controllers/main.py:86
#: code:addons/controllers/main.py:86
#, python-format
msgid "Check your email to activate your account!"
msgstr "メールアドレスへ会員登録ご案内メールが送信されました！"

#. module: auth_signup_verify_email
#: code:addons/auth_signup_verify_email/controllers/main.py:64
#: code:addons/controllers/main.py:64
#, python-format
msgid "Email is already exists"
msgstr "すでに登録されているメールアドレスです。"

#. module: auth_signup_verify_email
#: code:addons/auth_signup_verify_email/controllers/main.py:82
#: code:addons/controllers/main.py:82
#, python-format
msgid "Something went wrong, please try again later or contact us."
msgstr "問題が発生しました。もう一度メールアドレスを入力してください。"

#. module: auth_signup_verify_email
#: code:addons/auth_signup_verify_email/controllers/main.py:53
#: code:addons/controllers/main.py:53
#, python-format
msgid "That does not seem to be an email address."
msgstr "有効なメールアドレスを入力してください。"

#. module: auth_signup
#: code:addons/auth_signup/controllers/main.py:64
#, python-format
msgid "An email has been sent with credentials to reset your password"
msgstr "ご入力頂いたメールアドレスにパスワードリセットのURLを送信致しました。"

#. module: auth_signup
#: code:addons/auth_signup/controllers/main.py:38
#, python-format
msgid "Another user is already registered using this email address."
msgstr "ご入力頂いたメールアドレスはすでに登録されているため、登録できません。"

